### ISSUE TITLE
能否实现拉到底的时候再加载，而不是快拉到底时提前预加载

### ISSUE THREAD

**Issue by Smith-Curise** [hilongjw/vue-recyclerview#1]
能否实现拉到底的时候再加载，而不是快拉到底时提前预加载，因为这样的用户体验更好一点

**Comment by hilongjw** [comment]
目前实现的机制的持续滚动加载，如果数据暂未加载完成会使用 tombstone 占位。滚动到底部再加载不是很符合该组件的设计。

**Comment by shaoxiong789** [comment]
既然你的item 是绝对定位的，不懂你为啥还需要大量的tombstone隐藏元素来占位，好像没有必要

**Comment by hilongjw** [comment]
因为用户滑动是不确定的，预加载会提升滑动性能。其实也可以做的不使用 tombstone 占位

```html
 <RecyclerView 
      :prerender="1"
    ></RecyclerView>

```
