### ISSUE TITLE
Enhancement: Tombstone height defines how many elements get set in DOM

### ISSUE THREAD

**Issue by hazzo** [hilongjw/vue-recyclerview#11]
Hi, one question. Why when the tombstone is for example 1px I get more nodes in de the DOM and when it's higher I get less?

Although, if for example I set a tombstone with a height of more pixels than the chat messages the chunks of messages that I get are more separated from each other. The transform position its really offsetted. That did not happened on your chat demo (that actually now is not working 😛).

Thanks again!

**Comment by hilongjw** [comment]
RecyclerView will get the height of the tombstone, and predict and fill the tombstone according to the sliding distance. In my [demo](https://hilongjw.github.io/vue-recyclerview/#wechat-recyclerview) 's animation is working.

**Comment by hazzo** [comment]
Hmmm there is a way to avoid that distance between chunks? Even if means sacrificing the tombstone.
The only way I could remove that it was setting the tombstone to super small height. In that way the incoming items won't have that big separation between each. But the tombstones when they appear are extremely close.

**Comment by hilongjw** [comment]
@hazzo This is a problem, I'll try to solve it later.

**Comment by hilongjw** [comment]
@hazzo fixed at 0.3.3

**Comment by hazzo** [comment]
Great! Saw it genius!
