### ISSUE TITLE
Simplified usage

### ISSUE THREAD

**Issue by egoist** [hilongjw/vue-recyclerview#3]
I find it a little verbose and unnecessary to use this component like:

```js
components: {
   RecyclerView: RecyclerView(Vue)
}
```

---

Instead, maybe introduce a simplified usage, as plugin:

```js
import Vue from 'vue'
import { recyclerview } from 'recyclerview'

Vue.use(recyclerview)
```

As local component:

```js
import { RecyclerView } from 'recyclerview'

export default {
  components: { RecyclerView }
}
```

As global component:

```js
import Vue from 'vue'
import { RecyclerView } from 'recyclerview'

Vue.component(RecyclerView.name, RecyclerView)
```

**Comment by hilongjw** [comment]
it support plugin installation now. RecyclerView need Vue to create instance to render item of list, I think maybe the plugin would be better.

```javascript
import Vue from 'vue'
import recyclerview from 'recyclerview'

Vue.use(recyclerview)

```

```javascript
export default {
  components: { RecyclerView }
}
```

**Comment by egoist** [comment]
Thanks for the reply, sounds fair enough, it could be better if we can directly import the component for local registration, you can access `Vue` via `import Vue from 'vue'` directly. Anyways this is not an issue, closing :D
