### ISSUE TITLE
Append/Prepend/Update

### ISSUE THREAD

**Issue by hazzo** [hilongjw/vue-recyclerview#6]
Hi again @hilongjw sorry for opening another issue XD.

I was wondering if there is any method or way to append/prepend data to the recyclerview? Or make the view update with new pushed data to the array that has the data?

Uso of case: chat app. You have your recyclerview and an incoming message pushes to the array that has all the messages (stored in vuex for example) and recyclerview must update it's list with the new coming message.

Is this possible? 

Thanks again!

**Comment by hazzo** [comment]
Hi @hilongjw , I'm trying to use the `list` prop to get data from the recyclerview. 

I manage to get the data but pushing a new element into the array does update the list in my data and in the recyclerview component but does not appear in the DOM. Maybe I need to update the count? 

How should this be used to update the list and reproduce a common chat that appends a new message to array?

Thanks for answering to all my queries!!!

**Comment by hilongjw** [comment]
Try to call RecyclerView's internal methods
```javascript
RecyclerView.scroller.setItems(newList)
vm.$nextTick(() => {
   RecyclerView.scroller.onResize_()
})
```

**Comment by hazzo** [comment]
Doing so seems to be doing something but quite right. I mean the items increment in the array (the strange thing is if the list it's just one item longer It will show that has 2 more) but old messages and tombstone overlap ones I was sawing.

Here is a screencap:

![captura de pantalla 38](https://cloud.githubusercontent.com/assets/13692810/26771774/896570fc-49c1-11e7-99e5-d43bda30298e.png)

**Comment by hazzo** [comment]
Cool!
