### ISSUE TITLE
Suggestion: Start list from end

### ISSUE THREAD

**Issue by hazzo** [hilongjw/vue-recyclerview#7]
Hi again,

following the other issue (#6) of the chat app idea it would be great to have a method that let us start from the end of the list. I tried setting a scrollTop but as nodes are rendering when you scroll the real scrollHeight it's not known until you reach the far bottom.

Thnks again!

**Comment by hilongjw** [comment]
Hi @hazzo ,  I will add the `scrollToIndex ()` method to the RecyclerView instance, and it will also expose the `Items` array object in the RecyclerView to allow the data to be viewed or manipulated.

**Comment by hazzo** [comment]
Oh marvelous! Thanks very much again and congrats for the hard work!

**Comment by hazzo** [comment]
Hi @hilongjw again.
Y saw your new commits and npm versions. Thanks for adding this two features.
Some questions, the way of fetching data had changed?  Because before the update was working well until I updated. 
Another question, how list prop should be used? Passing it as prop that list array modifies the one provided by the fetch function? 

Thanks again for the quick implementations!
